package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String direccion;
	private String email;
	private Set cotizacions = new HashSet(0);
	private Set documentosclientes = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nombre, String apellidos, String direccion,
			String email, Set cotizacions, Set documentosclientes) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.email = email;
		this.cotizacions = cotizacions;
		this.documentosclientes = documentosclientes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getCotizacions() {
		return this.cotizacions;
	}

	public void setCotizacions(Set cotizacions) {
		this.cotizacions = cotizacions;
	}

	public Set getDocumentosclientes() {
		return this.documentosclientes;
	}

	public void setDocumentosclientes(Set documentosclientes) {
		this.documentosclientes = documentosclientes;
	}

}
