package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion implements java.io.Serializable {

	private int codigo;
	private Cliente cliente;
	private Date fecharegistro;
	private BigDecimal importetotal;
	private Set detallecotizacions = new HashSet(0);

	public Cotizacion() {
	}

	public Cotizacion(int codigo) {
		this.codigo = codigo;
	}

	public Cotizacion(int codigo, Cliente cliente, Date fecharegistro,
		BigDecimal importetotal, Set detallecotizacions) {
		this.codigo = codigo;
		this.cliente = cliente;
		this.fecharegistro = fecharegistro;
		this.importetotal = importetotal;
		this.detallecotizacions = detallecotizacions;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	public BigDecimal getImportetotal() {
		return this.importetotal;
	}

	public void setImportetotal(BigDecimal importetotal) {
		this.importetotal = importetotal;
	}

	public Set getDetallecotizacions() {
		return this.detallecotizacions;
	}

	public void setDetallecotizacions(Set detallecotizacions) {
		this.detallecotizacions = detallecotizacions;
	}

}
