package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sun.org.apache.xerces.internal.dom.DeepNodeListImpl;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion implements java.io.Serializable {

	private Integer codigo;
	private Cliente cliente;
	private Date fecharegistro;
	private BigDecimal importetotal;
	private Set<Detallecotizacion> detallecotizacions = new HashSet<Detallecotizacion>(0);

	public Cotizacion() {
		super();
	}

	public Cotizacion(int codigo) {
		this.codigo = codigo;
	}

	public Cotizacion(int codigo, Cliente cliente, Date fecharegistro,
		BigDecimal importetotal, Set<Detallecotizacion> detallecotizacions) {
		this.codigo = codigo;
		this.cliente = cliente;
		this.fecharegistro = fecharegistro;
		this.importetotal = importetotal;
		this.detallecotizacions = detallecotizacions;
	}
	
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	public BigDecimal getImportetotal() {
		return this.importetotal;
	}
	public BigDecimal getImporteIGV(){
		if(importetotal!=null)
			return this.importetotal.multiply(new BigDecimal(0.18).setScale(2, RoundingMode.CEILING));
		else
			return new BigDecimal(0.00);
	}
	public void setImportetotal(BigDecimal importetotal) {
		this.importetotal = importetotal;
	}

	public Set<Detallecotizacion> getDetallecotizacions() {
		return this.detallecotizacions;
	}

	public void setDetallecotizacions(Set<Detallecotizacion> detallecotizacions) {
		this.detallecotizacions = detallecotizacions;
	}

}
