package bean;
// Generated 18/10/2014 12:41:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.faces.event.ValueChangeEvent;

/**
 * Detallecotizacion generated by hbm2java
 */
public class Detallecotizacion implements java.io.Serializable {

	private Integer id;
	private Cotizacion cotizacion;
	private String codigo;
	private String descripcion;
	private Integer nrodepiezas;
	private BigDecimal precio;
	private BigDecimal importe;

	public Detallecotizacion() {
	}

	public Detallecotizacion(Cotizacion cotizacion, String codigo,
			String descripcion, Integer nrodepiezas, BigDecimal precio,
			BigDecimal importe) {
		this.cotizacion = cotizacion;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.nrodepiezas = nrodepiezas;
		this.precio = precio;
		this.importe = importe;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getNrodepiezas() {
		return this.nrodepiezas;
	}

	public void setNrodepiezas(Integer nrodepiezas) {
		this.nrodepiezas = nrodepiezas;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public void calcularImporteEnFuncionDeNroDePiezas(ValueChangeEvent event){
		BigDecimal importesito=new BigDecimal("0.0");
		Long nroDePiezas=(Long)event.getNewValue();
		if(nroDePiezas!=null && this.precio!=null){			
				importesito=new BigDecimal(String.valueOf(nroDePiezas)).multiply(precio);
				this.setImporte(importesito);			
		}
	}	

}
