package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Documentoscliente generated by hbm2java
 */
public class Documentoscliente implements java.io.Serializable {

	private DocumentosclienteId id;
	private Cliente cliente;
	private Documento documento;
	private String identificador;

	public Documentoscliente() {
	}

	public Documentoscliente(DocumentosclienteId id, Cliente cliente,
			Documento documento) {
		this.id = id;
		this.cliente = cliente;
		this.documento = documento;
	}

	public Documentoscliente(DocumentosclienteId id, Cliente cliente,
			Documento documento, String identificador) {
		this.id = id;
		this.cliente = cliente;
		this.documento = documento;
		this.identificador = identificador;
	}

	public DocumentosclienteId getId() {
		return this.id;
	}

	public void setId(DocumentosclienteId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

}
