package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * DocumentosclienteId generated by hbm2java
 */
public class DocumentosclienteId implements java.io.Serializable {

	private int idcliente;
	private int iddocumento;

	public DocumentosclienteId() {
	}

	public DocumentosclienteId(int idcliente, int iddocumento) {
		this.idcliente = idcliente;
		this.iddocumento = iddocumento;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public int getIddocumento() {
		return this.iddocumento;
	}

	public void setIddocumento(int iddocumento) {
		this.iddocumento = iddocumento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentosclienteId))
			return false;
		DocumentosclienteId castOther = (DocumentosclienteId) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& (this.getIddocumento() == castOther.getIddocumento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37 * result + this.getIddocumento();
		return result;
	}

}
