package bean;
// Generated 30/10/2014 03:42:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda implements java.io.Serializable {

	private int id;
	private String umon;
	private String umoneda;
	private Set productos = new HashSet(0);

	public Moneda() {
	}

	public Moneda(int id, String umon, String umoneda) {
		this.id = id;
		this.umon = umon;
		this.umoneda = umoneda;
	}

	public Moneda(int id, String umon, String umoneda, Set productos) {
		this.id = id;
		this.umon = umon;
		this.umoneda = umoneda;
		this.productos = productos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUmon() {
		return this.umon;
	}

	public void setUmon(String umon) {
		this.umon = umon;
	}

	public String getUmoneda() {
		return this.umoneda;
	}

	public void setUmoneda(String umoneda) {
		this.umoneda = umoneda;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
