package bean;
// Generated 30/10/2014 03:42:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private Integer codigo;
	private Cotizacion cotizacion;
	private Date fecharegistro;

	public Pedido() {
	}

	public Pedido(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	public Pedido(Cotizacion cotizacion, Date fecharegistro) {
		this.cotizacion = cotizacion;
		this.fecharegistro = fecharegistro;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

}
