package bean;

// Generated 30/09/2014 08:29:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int codigo;
	private Unidad unidad;
	private Integer espesor;
	private Integer ancho;
	private Integer largo;
	private String descripcion;
	public Producto() {
	}

	
	public Producto(int codigo) {
		this.codigo = codigo;
	}

	

	public Producto(int codigo, Unidad unidad, Integer espesor, Integer ancho,
			Integer largo, String descripcion) {
		super();
		this.codigo = codigo;
		this.unidad = unidad;
		this.espesor = espesor;
		this.ancho = ancho;
		this.largo = largo;
		this.descripcion = descripcion;
	}


	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Unidad getUnidad() {
		return this.unidad;
	}

	public void setUnidad(Unidad unidad) {
		this.unidad = unidad;
	}

	public Integer getEspesor() {
		return this.espesor;
	}

	public void setEspesor(Integer espesor) {
		this.espesor = espesor;
	}

	public Integer getAncho() {
		return this.ancho;
	}

	public void setAncho(Integer ancho) {
		this.ancho = ancho;
	}

	public Integer getLargo() {
		return this.largo;
	}

	public void setLargo(Integer largo) {
		this.largo = largo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
}
