package bean;
// Generated 30/10/2014 03:42:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Unidad generated by hbm2java
 */
public class Unidad implements java.io.Serializable {

	private int id;
	private String umedida;
	private Set productos = new HashSet(0);

	public Unidad() {
	}

	public Unidad(int id) {
		this.id = id;
	}

	public Unidad(int id, String umedida, Set productos) {
		this.id = id;
		this.umedida = umedida;
		this.productos = productos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUmedida() {
		return this.umedida;
	}

	public void setUmedida(String umedida) {
		this.umedida = umedida;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
